services:
  - type: web
    name: novel-summarizer
    env: node
    buildCommand: rm -rf node_modules && npm ci
    startCommand: npm start
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
    nodeVersion: 16
